from shoppingList import *

def test_operations():
    # ORMap and AWORSet operations
    # dc = DotContext()
    m1 = AWORMap()
    m2 = AWORMap()
    m1.add("pablo","color", "red")
    m1.add("pablo", "color", "blue")
    m2.add("pablo", "taste", "bitter")
    m2.add("pablo", "color", "green")
    print(m2.entries["taste"])
    m1.merge(m2)
    print(m1.entries["color"])
    m1.rem("taste")
    print(m1.entries.get("taste", "Not found"))

    # # AWORSet operations
    # s1 = AWORSet("x", dc)
    # s2 = AWORSet("x", dc)
    # s1.add(1)
    # s2.add(2)
    # print(s1)
    # print(s2)

    # # ORMap with AWORSet operations
    # dc2 = DotContext()
    # m3 = ORMap("x", dc)
    # m4 = ORMap("y", dc2)
    # m3.add("color", "red")
    # m3.add("color", "blue")
    # m4.add("color", "green")
    # print(m3["color"])
    # print(m4["color"])
    # m3.merge(m4)
    # print(m3["color"])
    # m3["color"].remove("green")
    # m3.merge(m4)
    # print(m3["color"])

    # # ORMap with deltas
    # mx = ORMap("x", dc)
    # d1 = ORMap("x", dc)
    # d2 = ORMap("x", dc)
    # mx.add("color", "red")
    # mx.add("color", "blue")
    # d1.remove("color")
    # d2.add("color", "black")
    # print(d1)
    # print(d2)

    # # CCounter operations
    # cc1 = CCounter("x")
    # cc2 = CCounter("y")
    # cc1.inc(10)
    # cc2.merge(cc1)
    # cc2.inc(10)
    # print(cc1)
    # cc1.inc()
    # print(cc1)
    # cc1.dec()
    # print(cc1)
    # cc1.reset()
    # print(cc1)
    # print(cc1.read())
    # cc1.inc(5)
    # cc1.merge(cc2)
    # print(cc1)
    # print(cc1.read())

    # # Nested ORMap operations
    # m5 = ORMap("x", dc)
    # m6 = ORMap("y", dc)
    # m5.add("color", "red")
    # m5.add("taste", "bitter")
    # m6.add("sound", "loud")
    # m6.add("color", "blue")
    # print("m5", m5)
    # print("m6", m6)
    # m5.merge(m6)
    # print("m5", m5)
    # m6.remove("sound")
    # print("m6", m6)
    # m5.merge(m6)
    # print("m5", m5)
    # m5.remove("color")
    # m5.reset()
    # print("m5", m5)
    # m5.merge(m6)
    # print("m5", m5)

    # # Nested ORMap with AWORSet
    # m7 = ORMap("x", dc)
    # m7.add(2, "color")
    # m7[2].add("red")
    # print(m7)

test_operations()